package route_test

import (
	"errors"
	"sync"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/vukamecos/unverified/internal/contract/route"
)

// The tests in this file exercise the [route.Link] interface via the
// moq-generated [route.LinkMock] (regenerated by `go generate ./...`,
// do not edit by hand per ARCH §13.1).
//
// These are *contract* tests for the interface itself: they pin the
// behavioural properties callers depend on — idempotency, typed
// error propagation, and the Reason-extraction path through wrapped
// errors — using a configurable mock rather than any concrete
// implementation. The mock lets us assert that the *interface*
// exposes what callers expect, independent of the iproute2-backed
// production impl.

// newIdempotentLink returns a LinkMock whose Up / Down / AddAddress
// are idempotent on a per-instance basis: the first call records the
// argument and returns nil; subsequent calls with the same argument
// return nil; calls with a *different* argument for AddAddress
// return ReasonAddressAlreadyAssigned.
//
// The mock is the ground-truth "what an idempotent Link looks like"
// — any production impl that does not match this behaviour on the
// relevant property has a contract bug, not a mock bug.
func newIdempotentLink() *route.LinkMock {
	m := &route.LinkMock{
		UpFunc:   func() error { return nil },
		DownFunc: func() error { return nil },
	}
	var mu sync.Mutex
	var assigned string
	m.AddAddressFunc = func(cidr string) error {
		mu.Lock()
		defer mu.Unlock()
		if assigned == "" {
			assigned = cidr
			return nil
		}
		if assigned == cidr {
			return nil
		}
		return &route.LinkError{
			Reason: route.ReasonAddressAlreadyAssigned,
			Cause:  errors.New("mock: conflicting address"),
		}
	}
	return m
}

// TestLinkMock_ImplementsLink is a compile-time check: the mock
// must satisfy [route.Link]. The mock's own file has a `var _ Link =
// &LinkMock{}` assertion; this test exists so the dependency shows
// up in the test binary's symbol table and a future migration that
// removes the var assertion still fails the test gate.
func TestLinkMock_ImplementsLink(t *testing.T) {
	t.Parallel()
	var _ route.Link = (*route.LinkMock)(nil)
}

// TestLinkContract_UpIdempotent verifies that a correctly-implemented
// Link reports Up idempotent at the mock level. The mock is
// configured to return nil for every Up; the contract test asserts
// that calls are recorded and the same instance can be called
// repeatedly without state change.
func TestLinkContract_UpIdempotent(t *testing.T) {
	t.Parallel()
	m := newIdempotentLink()
	for i := 0; i < 3; i++ {
		require.NoError(t, m.Up(), "Up() #%d must be nil for an idempotent Link", i)
	}
	assert.Len(t, m.UpCalls(), 3, "every Up call must be recorded")
}

// TestLinkContract_DownIdempotent mirrors TestLinkContract_UpIdempotent
// for Down.
func TestLinkContract_DownIdempotent(t *testing.T) {
	t.Parallel()
	m := newIdempotentLink()
	for i := 0; i < 3; i++ {
		require.NoError(t, m.Down(), "Down() #%d must be nil for an idempotent Link", i)
	}
	assert.Len(t, m.DownCalls(), 3, "every Down call must be recorded")
}

// TestLinkContract_AddAddress_IdempotentSameCIDR verifies that
// re-adding the same CIDR is a no-op. The mock reflects the expected
// production semantics: first call records, second call with the
// same CIDR is a no-op (no error, no state change).
func TestLinkContract_AddAddress_IdempotentSameCIDR(t *testing.T) {
	t.Parallel()
	m := newIdempotentLink()
	require.NoError(t, m.AddAddress("10.66.0.2/24"),
		"first AddAddress must succeed")
	require.NoError(t, m.AddAddress("10.66.0.2/24"),
		"re-adding the SAME CIDR must be a no-op (idempotency contract)")
	calls := m.AddAddressCalls()
	require.Len(t, calls, 2,
		"both calls must be recorded, even though the second is a no-op")
	assert.Equal(t, "10.66.0.2/24", calls[0].Cidr)
	assert.Equal(t, "10.66.0.2/24", calls[1].Cidr)
}

// TestLinkContract_AddAddress_DifferentCIDR_TypedError verifies
// that the typed-error path is observable through the Link
// interface: a caller that branches on LinkReason sees the right
// Reason without parsing the error message.
func TestLinkContract_AddAddress_DifferentCIDR_TypedError(t *testing.T) {
	t.Parallel()
	m := newIdempotentLink()
	require.NoError(t, m.AddAddress("10.66.0.2/24"))
	err := m.AddAddress("10.66.0.3/24")
	require.Error(t, err)
	assert.True(t, route.IsLinkError(err),
		"the error returned by a Link impl on conflicting CIDR must be a *LinkError")
	assert.Equal(t, route.ReasonAddressAlreadyAssigned, route.LinkReason(err),
		"LinkReason must return the stable Reason string callers switch on")
}

// TestLinkContract_AddAddress_DifferentCIDR_WrappedUnwrap verifies
// that the typed error survives wrapping via fmt.Errorf("%w") —
// callers commonly wrap Link errors with additional context ("at
// startup", "for tunnel X"), and the contract helpers must still
// extract the Reason from the wrapped chain.
func TestLinkContract_AddAddress_DifferentCIDR_WrappedUnwrap(t *testing.T) {
	t.Parallel()
	m := newIdempotentLink()
	require.NoError(t, m.AddAddress("10.66.0.2/24"))
	rawErr := m.AddAddress("10.66.0.3/24")
	require.Error(t, rawErr)

	wrapped := errors.Join(errors.New("tunnel bring-up"), rawErr)

	assert.True(t, route.IsLinkError(wrapped),
		"IsLinkError must walk the wrap chain via errors.As")
	assert.Equal(t, route.ReasonAddressAlreadyAssigned, route.LinkReason(wrapped),
		"LinkReason must walk the wrap chain via errors.As")
}

// TestLinkContract_AllReasons_RoundTrip exercises every Reason
// constant through a Link-shaped path: the mock returns each
// Reason in turn, and the contract helpers must surface it
// unchanged. This is the inverse of TestLinkReason_Stability —
// that one pins the strings; this one pins that the helpers
// preserve them through the interface.
func TestLinkContract_AllReasons_RoundTrip(t *testing.T) {
	t.Parallel()
	reasons := []string{
		route.ReasonUnsupportedPlatform,
		route.ReasonBinaryNotFound,
		route.ReasonCIDRInvalid,
		route.ReasonLinkUpFailed,
		route.ReasonLinkDownFailed,
		route.ReasonAddressAlreadyAssigned,
		route.ReasonAddressAddFailed,
	}
	for _, r := range reasons {
		r := r
		t.Run(r, func(t *testing.T) {
			t.Parallel()
			linkErr := &route.LinkError{Reason: r}
			// Surface through a Link-shaped path: wrap and unwrap.
			wrapped := errors.Join(errors.New("context"), linkErr)
			assert.True(t, route.IsLinkError(wrapped),
				"IsLinkError must accept the wrapped *LinkError for reason %q", r)
			assert.Equal(t, r, route.LinkReason(wrapped),
				"LinkReason must return %q unchanged through a wrap chain", r)
		})
	}
}

// TestLinkContract_CallRecordingConcurrency verifies that the
// moq-generated mock is safe to use from multiple goroutines. The
// production impl explicitly documents single-goroutine use; this
// test pins the *mock's* own threading model so callers do not
// accidentally rely on it. (The mock uses sync.RWMutex internally;
// this test fails visibly if a future moq release drops the locks.)
func TestLinkContract_CallRecordingConcurrency(t *testing.T) {
	t.Parallel()
	m := newIdempotentLink()
	const goroutines = 16
	const callsPerGoroutine = 64

	var wg sync.WaitGroup
	wg.Add(goroutines)
	for g := 0; g < goroutines; g++ {
		go func() {
			defer wg.Done()
			for i := 0; i < callsPerGoroutine; i++ {
				_ = m.Up()
				_ = m.Down()
				_ = m.AddAddress("10.66.0.2/24")
			}
		}()
	}
	wg.Wait()

	assert.Equal(t, goroutines*callsPerGoroutine, len(m.UpCalls()),
		"mock Up recording must be race-free")
	assert.Equal(t, goroutines*callsPerGoroutine, len(m.DownCalls()),
		"mock Down recording must be race-free")
	assert.Equal(t, goroutines*callsPerGoroutine, len(m.AddAddressCalls()),
		"mock AddAddress recording must be race-free")
}