// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package route

import (
	"sync"
)

// Ensure, that LinkMock does implement Link.
// If this is not the case, regenerate this file with moq.
var _ Link = &LinkMock{}

// LinkMock is a mock implementation of Link.
//
//	func TestSomethingThatUsesLink(t *testing.T) {
//
//		// make and configure a mocked Link
//		mockedLink := &LinkMock{
//			AddAddressFunc: func(cidr string) error {
//				panic("mock out the AddAddress method")
//			},
//			DownFunc: func() error {
//				panic("mock out the Down method")
//			},
//			UpFunc: func() error {
//				panic("mock out the Up method")
//			},
//		}
//
//		// use mockedLink in code that requires Link
//		// and then make assertions.
//
//	}
type LinkMock struct {
	// AddAddressFunc mocks the AddAddress method.
	AddAddressFunc func(cidr string) error

	// DownFunc mocks the Down method.
	DownFunc func() error

	// UpFunc mocks the Up method.
	UpFunc func() error

	// calls tracks calls to the methods.
	calls struct {
		// AddAddress holds details about calls to the AddAddress method.
		AddAddress []struct {
			// Cidr is the cidr argument value.
			Cidr string
		}
		// Down holds details about calls to the Down method.
		Down []struct {
		}
		// Up holds details about calls to the Up method.
		Up []struct {
		}
	}
	lockAddAddress sync.RWMutex
	lockDown       sync.RWMutex
	lockUp         sync.RWMutex
}

// AddAddress calls AddAddressFunc.
func (mock *LinkMock) AddAddress(cidr string) error {
	if mock.AddAddressFunc == nil {
		panic("LinkMock.AddAddressFunc: method is nil but Link.AddAddress was just called")
	}
	callInfo := struct {
		Cidr string
	}{
		Cidr: cidr,
	}
	mock.lockAddAddress.Lock()
	mock.calls.AddAddress = append(mock.calls.AddAddress, callInfo)
	mock.lockAddAddress.Unlock()
	return mock.AddAddressFunc(cidr)
}

// AddAddressCalls gets all the calls that were made to AddAddress.
// Check the length with:
//
//	len(mockedLink.AddAddressCalls())
func (mock *LinkMock) AddAddressCalls() []struct {
	Cidr string
} {
	var calls []struct {
		Cidr string
	}
	mock.lockAddAddress.RLock()
	calls = mock.calls.AddAddress
	mock.lockAddAddress.RUnlock()
	return calls
}

// Down calls DownFunc.
func (mock *LinkMock) Down() error {
	if mock.DownFunc == nil {
		panic("LinkMock.DownFunc: method is nil but Link.Down was just called")
	}
	callInfo := struct {
	}{}
	mock.lockDown.Lock()
	mock.calls.Down = append(mock.calls.Down, callInfo)
	mock.lockDown.Unlock()
	return mock.DownFunc()
}

// DownCalls gets all the calls that were made to Down.
// Check the length with:
//
//	len(mockedLink.DownCalls())
func (mock *LinkMock) DownCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockDown.RLock()
	calls = mock.calls.Down
	mock.lockDown.RUnlock()
	return calls
}

// Up calls UpFunc.
func (mock *LinkMock) Up() error {
	if mock.UpFunc == nil {
		panic("LinkMock.UpFunc: method is nil but Link.Up was just called")
	}
	callInfo := struct {
	}{}
	mock.lockUp.Lock()
	mock.calls.Up = append(mock.calls.Up, callInfo)
	mock.lockUp.Unlock()
	return mock.UpFunc()
}

// UpCalls gets all the calls that were made to Up.
// Check the length with:
//
//	len(mockedLink.UpCalls())
func (mock *LinkMock) UpCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockUp.RLock()
	calls = mock.calls.Up
	mock.lockUp.RUnlock()
	return calls
}
