// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package session

import (
	"context"
	"github.com/vukamecos/unverified/internal/contract/transport"
	contracttun "github.com/vukamecos/unverified/internal/contract/tun"
	"sync"
)

// Ensure, that PumpMock does implement Pump.
// If this is not the case, regenerate this file with moq.
var _ Pump = &PumpMock{}

// PumpMock is a mock implementation of Pump.
//
//	func TestSomethingThatUsesPump(t *testing.T) {
//
//		// make and configure a mocked Pump
//		mockedPump := &PumpMock{
//			RunFunc: func(ctx context.Context, dev contracttun.Device, tun transport.Tunnel) error {
//				panic("mock out the Run method")
//			},
//		}
//
//		// use mockedPump in code that requires Pump
//		// and then make assertions.
//
//	}
type PumpMock struct {
	// RunFunc mocks the Run method.
	RunFunc func(ctx context.Context, dev contracttun.Device, tun transport.Tunnel) error

	// calls tracks calls to the methods.
	calls struct {
		// Run holds details about calls to the Run method.
		Run []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Dev is the dev argument value.
			Dev contracttun.Device
			// Tun is the tun argument value.
			Tun transport.Tunnel
		}
	}
	lockRun sync.RWMutex
}

// Run calls RunFunc.
func (mock *PumpMock) Run(ctx context.Context, dev contracttun.Device, tun transport.Tunnel) error {
	if mock.RunFunc == nil {
		panic("PumpMock.RunFunc: method is nil but Pump.Run was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Dev contracttun.Device
		Tun transport.Tunnel
	}{
		Ctx: ctx,
		Dev: dev,
		Tun: tun,
	}
	mock.lockRun.Lock()
	mock.calls.Run = append(mock.calls.Run, callInfo)
	mock.lockRun.Unlock()
	return mock.RunFunc(ctx, dev, tun)
}

// RunCalls gets all the calls that were made to Run.
// Check the length with:
//
//	len(mockedPump.RunCalls())
func (mock *PumpMock) RunCalls() []struct {
	Ctx context.Context
	Dev contracttun.Device
	Tun transport.Tunnel
} {
	var calls []struct {
		Ctx context.Context
		Dev contracttun.Device
		Tun transport.Tunnel
	}
	mock.lockRun.RLock()
	calls = mock.calls.Run
	mock.lockRun.RUnlock()
	return calls
}
